//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.07.17 at 11:28:57 AM EEST
//

package com.gillsoft.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="currency" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="r030" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="txt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="rate" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="cc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="exchangedate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"currency"})
@XmlRootElement(name = "exchange")
public class Exchange {

  protected List<Exchange.Currency> currency;

  /**
   * Gets the value of the currency property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the currency property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getCurrency().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link Exchange.Currency }
   * 
   * 
   */
  public List<Exchange.Currency> getCurrency() {
    if (currency == null) {
      currency = new ArrayList<Exchange.Currency>();
    }
    return this.currency;
  }

  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="r030" type="{http://www.w3.org/2001/XMLSchema}short"/>
   *         &lt;element name="txt" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="rate" type="{http://www.w3.org/2001/XMLSchema}float"/>
   *         &lt;element name="cc" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="exchangedate" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"r030", "txt", "rate", "cc", "exchangedate"})
  public static class Currency {

    protected short r030;
    @XmlElement(required = true)
    protected String txt;
    protected float rate;
    @XmlElement(required = true)
    protected String cc;
    @XmlElement(required = true)
    protected String exchangedate;

    /**
     * Gets the value of the r030 property.
     * 
     */
    public short getR030() {
      return r030;
    }

    /**
     * Sets the value of the r030 property.
     * 
     */
    public void setR030(short value) {
      this.r030 = value;
    }

    /**
     * Gets the value of the txt property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTxt() {
      return txt;
    }

    /**
     * Sets the value of the txt property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTxt(String value) {
      this.txt = value;
    }

    /**
     * Gets the value of the rate property.
     * 
     */
    public float getRate() {
      return rate;
    }

    /**
     * Sets the value of the rate property.
     * 
     */
    public void setRate(float value) {
      this.rate = value;
    }

    /**
     * Gets the value of the cc property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCc() {
      return cc;
    }

    /**
     * Sets the value of the cc property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCc(String value) {
      this.cc = value;
    }

    /**
     * Gets the value of the exchangedate property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getExchangedate() {
      return exchangedate;
    }

    /**
     * Sets the value of the exchangedate property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setExchangedate(String value) {
      this.exchangedate = value;
    }

  }

}
